app/pitches/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, RadioField
from wtforms.validators import DataRequired
from app.models import Comment

class PitchForm(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  content = TextAreaField('Content', validators=[DataRequired()])
  category = RadioField('Category',  choices=[('pickuplines','pickuplines'), ('elevatorpitch','elevatorpitch') ,('productpitch','productpitch'), ('randompitch','randompitch')], validators=[DataRequired()])
  submit = SubmitField('Post')

class CommentForm(FlaskForm):
	content = TextAreaField('Add comment', validators=[DataRequired()])
	submit = SubmitField('Post')

app/pitches/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from flask_login import current_user, login_required
from app import db
from app.models import Pitch, Comment, Upvote, Downvote
from app.pitches.forms import PitchForm,  CommentForm


pitches = Blueprint('pitches', __name__)

@pitches.route('/pitch/new', methods=['GET', 'POST'])
@login_required
def new_pitch():
  form = PitchForm()
  if form.validate_on_submit():
    pitch = Pitch(title=form.title.data, content=form.content.data, category=form.category.data, author=current_user)
    db.session.add(pitch)
    db.session.commit()
    flash('Your pitch has been posted!', 'success')
    return redirect(url_for('main.index'))
  return render_template('create_pitch.html', title='New Pitch', form=form, legend='New Post')

@pitches.route('/pitch/<int:pitch_id>', methods=['GET', 'POST'])
@login_required
def new_comment(pitch_id):
  pitch = Pitch.query.get_or_404(pitch_id)
  form =  CommentForm()

  if form.validate_on_submit():
    comment = Comment(content=form.content.data, author=current_user, pitch_id = pitch_id)
    db.session.add(comment)
    db.session.commit()
    flash('Your comment has been posted!', 'success')
    return redirect(url_for('pitches.new_comment', pitch_id= pitch_id))
    
  all_comments = Comment.query.filter_by(pitch_id = pitch_id).all()

  return render_template('pitch.html', form=form, legend='Leave a Comment', pitch=pitch, comments=all_comments, title=pitch.title)


@pitches.route('/pitch/<int:pitch_id>/update', methods=['GET', 'POST'])
@login_required
def update_pitch(pitch_id):
  pitch = Pitch.query.get_or_404(pitch_id)
  if pitch.author != current_user:
    abort(403)
  form = PitchForm()
  if form.validate_on_submit():
    pitch.title = form.title.data
    pitch.content = form.content.data
    db.session.commit()
    flash('Your pitch has been updated', 'success')
    return redirect(url_for('pitches.new_comment', pitch_id=pitch_id))
  elif request.method == 'GET':
    form.title.data = pitch.title
    form.content.data = pitch.content
  return render_template('create_pitch.html', title='Update Pitch', form=form, legend='Update Pitch')

@pitches.route('/pitch/<int:pitch_id>/delete', methods=['POST'])
@login_required
def delete_pitch(pitch_id):
  pitch = Pitch.query.get_or_404(pitch_id)
  if pitch.author != current_user:
    abort(403)
  db.session.delete(pitch)
  db.session.commit()
  flash('Your pitch has been deleted', 'success')
  return redirect(url_for('main.index'))


@pitches.route('/pitch/<int:pitch_id>/upvote', methods = ['GET', 'POST'])
@login_required
def upvote(pitch_id):
    pitch = Pitch.query.get(pitch_id)
    user = current_user
    pitch_upvotes = Upvote.query.filter_by(pitch_id= pitch_id)
    if Upvote.query.filter(Upvote.user_id==user.id, Upvote.pitch_id==pitch_id).first():
        return  redirect(url_for('main.index'))

    new_upvote = Upvote(pitch_id=pitch_id, author=current_user)
    new_upvote.save_upvotes()
    return redirect(url_for('main.index'))

@pitches.route('/pitch/<int:pitch_id>/downvote', methods = ['GET', 'POST'])
@login_required
def downvote(pitch_id):
    pitch = Pitch.query.get(pitch_id)
    user = current_user
    pitch_upvotes = Downvote.query.filter_by(pitch_id= pitch_id)
    if Downvote.query.filter(Downvote.user_id==user.id, Downvote.pitch_id==pitch_id).first():
      return  redirect(url_for('main.index'))

    new_downvote = Downvote(pitch_id=pitch_id, author=current_user)
    new_downvote.save_downvotes()
    return redirect(url_for('main.index'))

@pitches.route('/categories/<string:cat_name>')
def category(cat_name):
    '''
    function to return the pitches by category
    '''
    category = Pitch.get_pitches(cat_name)

    return render_template('categories.html', category = category, title=cat_name)

app/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User, Pitch
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from app.users.utlis import save_profile_picture, send_reset_email, send_welcome_email

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('main.index'))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user = User(username=form.username.data, email = form.email.data, password = hashed_password)
    db.session.add(user)
    db.session.commit()
    user_email = user.email
    send_welcome_email(user_email)

    flash(f'Hello { form.username.data}, Your Account was created succesfully! You are now able to log in', 'success')
    return redirect(url_for('users.login'))
  return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
  if current_user.is_authenticated:
    return redirect(url_for('main.index'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get('next')
      return redirect(next_page) if next_page else redirect(url_for('main.index'))   
    else:
      flash('Login Unsuccessful. Please check email and password', 'danger')

  return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
  logout_user()
  return redirect (url_for('main.index'))

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
  if current_user.is_authenticated:
    return redirect(url_for('main.index'))
  form = RequestResetForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    send_reset_email(user)
    flash('Check your email for a link to reset your password.', 'info')
    return redirect(url_for('users.login'))
  return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token): 
  if current_user.is_authenticated:
    return redirect(url_for('main.index'))
  user = User.verify_reset_token(token)
  if user is None:
    flash('The reset token has either expired or is invalid', 'warning')
    return redirect(url_for('users.reset_request'))
  form = ResetPasswordForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user.password = hashed_password
    db.session.commit()
    flash('Your password has been updated! You can now login to your account', 'success')
    return redirect(url_for('users.login'))
  return render_template('reset_token.html', title='Reset Password', form=form)

@users.route('/user/<string:username>')
def user_account(username):
  user = User.query.filter_by(username=username).first_or_404()
  pitches = Pitch.query.filter_by(author=user).order_by(Pitch.pub_date.desc())
  image_file= url_for('static', filename=f'images/{user.image_file}')
  return render_template('profile.html', pitches=pitches, user=user, image_file=image_file,)

@users.route('/update_account', methods=['GET', 'POST'])
@login_required
def update_account():
  form = UpdateAccountForm()
  if form.validate_on_submit():
    if form.picture.data:
      picture_file =  save_profile_picture(form.picture.data)
      current_user.image_file = picture_file
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash('Your account information has been updated!', 'success')
    return redirect(url_for('users.update_account'))
  elif request.method == 'GET':
    form.username.data = current_user.username
    form.email.data = current_user.email
  image_file= url_for('static', filename=f'images/{current_user.image_file}')
  return render_template('update_account.html', title='Account', image_file=image_file, form=form)

app/templates/account.html
{% extends 'layout.html' %}

{% block content %}
  <div class="content">
    <div class="row">
      <div class="col-md-6">
        <div class="media">
          <img src="{{ image_file }}" alt="" class="rounded-circle account-img">
          <div class="media-body">
            <h2 class="account-heading"> {{ current_user.username }}</h2>
            <p class="text-secondary"> {{ current_user.email }}</p>
          </div>
        </div>
        {% for pitch in pitches %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + pitch.author.image_file)}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ pitch.author.username }}</a>
              <small class="text-muted">{{ pitch.pub_date.strftime('%Y/%m/%d')}}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('pitches.new_comment', pitch_id=pitch.id)}}">{{ pitch.title }}</a></h2>
            <p class="article-content">{{ pitch.content }}</p>
            <div>
              <a href="{{url_for('pitches.new_comment', pitch_id = pitch.id)}}"><button><i class="fa fa-comments"></i></button></a>
              <a href="{{url_for('pitches.upvote', pitch_id = pitch.id)}}"><button><i class="fa fa-thumbs-up">{{ pitch.upvotes.count() }}</i> </button></a>
              <a href="{{url_for('pitches.downvote', pitch_id = pitch.id)}}"><button><i class="fa fa-thumbs-down">{{ pitch.downvotes.count() }}</i></button></a>
            </div>
          </div>
        </article>
        {% endfor %}
      </div>
      <div class="col-md-6">
        <div class="register-form">
          <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4"> Account Info </legend>
              <div class="form-group">
                {{ form.username.label (class="form-control-label") }}
      
                {% if form.username.errors %}
                  {{ form.username (class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                 {% else %} 
                  {{ form.username (class="form-control form-control-lg") }}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.email.label (class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} 
                {{ form.email (class="form-control form-control-lg") }}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.picture.label () }}
                {{ form.picture (class="form-control-file") }}
                {% if form.picture.errors %}
                  {% for error in form.picture.errors %}
                  <span class="text-danger">{{ error }}</span>
                  {% endfor %}
                {% endif %}
              </div>
            </fieldset>
            <div class="form-group">
              {{ form.submit (class="btn btn-outline-info") }}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/categories.html
{% extends 'layout.html' %}
{% block content %}
  <div class="container">
    {% for cat in category %}
      <div class="card m-4">
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + cat.author.image_file)}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ cat.author.username }}</a> 
              <p class="tag"><i class="fa fa-tags"></i>{{ cat.category }}</p>
            </div>
            <h2><a class="article-title" href="{{ url_for('pitches.new_comment', pitch_id=cat.id)}}">{{ cat.title }}</a></h2>
            <p class="article-content">{{ cat.content }}</p>
            <div>
              <a href="{{url_for('pitches.new_comment', pitch_id = cat.id)}}"><i class="fa fa-comments"></i></a>
              <a href="{{url_for('pitches.upvote', pitch_id = cat.id)}}"><i class="fa fa-thumbs-up">{{ cat.upvotes.count() }}</i></a>
              <a href="{{url_for('pitches.downvote', pitch_id = cat.id)}}"><i class="fa fa-thumbs-down">{{ cat.downvotes.count() }}</i></a>
              <small class="text-muted tag" style="margin: 15px;"><b>Posted on:</b> {{cat.pub_date.strftime('%Y/%m/%d')}}</small>           
            </div>
          </div>
        </article>
      </div>  
    {% endfor %}
  </div>
{% endblock content %}

app/templates/create_pitch.html
{% extends 'layout.html' %}

{% block content %}
  <div id="particles-js">
    <div class="container">
      <div class="card sign-up-login-form">
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4"> {{ legend }}</legend>
            <div class="form-group">
              {{ form.title.label (class="form-control-label") }}
              {% if form.title.errors %}
              {{ form.title(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} 
              {{ form.title (class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.content.label (class="form-control-label") }}
              {% if form.content.errors %}
              {{ form.content (class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.content.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} 
              {{ form.content (class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div>
              {{ form.category.label  }}
              {% if form.category.errors %}
              {{ form.category (class="is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.category.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} 
              {{ form.category }}
              {% endif %}
            </div>
          </fieldset>
          <div class="form-group">
            {{ form.submit (class="btn btn-outline-info") }}
          </div>
        </form>
      </div>
    </div>  
  </div>
 
{% endblock content %}

app/templates/index.html
{% import 'macros.html' as macro%}

{% extends "layout.html" %}
{% block content %}

  <div class="container all-pitches">
    <div class="row">
      <div class="col-md-9">
        {{ macro.displayPitchList(pitches) }}
      </div>
      
        <div class="category-section col-md-3">
          <div class="card">
          <h3 class="article-title text-center mt-3"><b>All Categories</b></h3>
            <ul class="list-unstyled">     
              <li class="list-group-item"><a href="/categories/productpitch">Product Pitch</a></li>
              <li class="list-group-item"><a href="/categories/elevatorpitch">Elevator Pitch</a></li>
              <li class="list-group-item"> <a href="/categories/pickuplines">Pickup Line</a></li>
              <li class="list-group-item"><a href="/categories/randompitch">Random Pitch</a></li>
            </ul>
        </div>
      </div>
      
    </div>
  </div> 

 
{% endblock content %}

app/templates/login.html
{% extends 'layout.html' %}

{% block content %}
  <div id="particles-js">
    <div class="cotainer">
      <div class="card sign-up-login-form">
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4 legend"> Log In </legend>
            <div class="form-group">
              {{ form.email.label (class="form-control-label") }}
              {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} 
              {{ form.email (class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.password.label (class="form-control-label") }}
              {% if form.password.errors %}
              {{ form.password (class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} 
              {{ form.password (class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-check">
              {{ form.remember(class ="form-check-input") }}
              {{ form.remember.label (class ="form-check-label") }}
            </div>
          </fieldset>
          <div class="form-group">
            {{ form.submit (class="btn btn-outline-info") }}
            <small class="text-muted-ml-2">
              <a href="{{ url_for('users.reset_request') }}"> Forgot Password?</a>
            </small>
          </div>
        </form> 
        <div class="border-top pt-4">
          <small class="text-muted">
            Need An Account? <a href="{{ url_for('users.register') }}" class="ml-2"> Sign Up Here</a>
          </small>
        </div>
      </div>
    </div>
  </div>    
{% endblock content %}

app/templates/macros.html
{% macro displayPitchList(pitches) %}

  {% for pitch in pitches %}
    <div class="card m-4 all-pitches">
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + pitch.author.image_file)}}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for ('users.user_account', username=pitch.author.username) }}">{{ pitch.author.username }}</a>
           <p class="tag"><i class="fa fa-tags"></i>{{ pitch.category }}</p>
          </div>
          <h2><a class="article-title" href="{{ url_for('pitches.new_comment', pitch_id=pitch.id)}}">{{ pitch.title }}</a></h2>
          <p class="article-content">{{ pitch.content }}</p>
          <div>
            <a href="{{url_for('pitches.new_comment', pitch_id = pitch.id)}}"><i class="fa fa-comments"></i></a>
            <a href="{{url_for('pitches.upvote', pitch_id = pitch.id)}}"><i class="fa fa-thumbs-up">{{ pitch.upvotes.count() }}</i></a>
            <a href="{{url_for('pitches.downvote', pitch_id = pitch.id)}}"><i class="fa fa-thumbs-down">{{ pitch.downvotes.count() }}</i></a>
            <small class="text-muted tag" style="margin: 15px;"><b>Posted on:</b> {{ pitch.pub_date.strftime('%Y/%m/%d')}}</small>
          </div>
        </div>
      </article>  
    </div>
  {% endfor %}

{% endmacro %}

app/templates/navbar.html
<nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
  <a class="navbar-brand" href="#">PitchCapital</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.index') }}">Home
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">Categories
        </a>
        <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="/categories/productpitch">Product Pitch</a>
          <a class="dropdown-item" href="/categories/elevatorpitch">Elevator Pitch</a>
          <a class="dropdown-item" href="/categories/pickuplines">Pickup Lines</a>
          <a class="dropdown-item" href="/categories/randompitch">Random Pitch</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fa fa-facebook"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fa fa-twitter"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fa fa-instagram"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fab fa-google-plus-g"></i>
        </a>
      </li>
      {% if current_user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="{{ url_for('pitches.new_pitch') }}">New Pitch</a>
          <a class="dropdown-item" href="{{ url_for('users.user_account', username=current_user.username) }}">My Profile</a>
          <a class="dropdown-item" href="{{ url_for('users.update_account') }}">Update Account</a>
          <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.register') }}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.login') }}">Log in</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

app/templates/pitch.html
{% extends "layout.html" %}
{% block content %}
  <div class="container">
    <div class="card">
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + pitch.author.image_file)}}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ pitch.author.username }}</a>
            <small class="text-muted">{{ pitch.pub_date.strftime('%Y/%m/%d')}}</small>
            {% if pitch.author == current_user %}
              <div>
                <a href="{{ url_for('pitches.update_pitch', pitch_id=pitch.id)}}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
                <button type="button" class="btn btn-danger btn-sm ml-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
              </div>
            {% endif %}
          </div>
          <h2 class="article-title">{{ pitch.title }}</h2>
          <p class="article-content">{{ pitch.content }}</p>
        </div>
      </article>
    </div> 
    <div class="comment-form">
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4"> {{ legend }} </legend>
          <div class="form-group">
            {{ form.content.label (class="form-control-label") }}
            {% if form.content.errors %}
            {{ form.content (class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.content.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} 
            {{ form.content (class="form-control form-control-lg") }}
            {% endif %}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit (class="btn btn-outline-info") }}
        </div>
      </form>
    </div>
  {% if comments %}  
  {% for comment in comments %}
    <div class="card">
      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ comment.author.username }}</a>
            <small class="text-muted">{{ comment.date_posted.strftime('%Y/%m/%d')}}</small>
          </div>
          <p class="article-content">{{ comment.content }}</p>
          <div>
            <i class="fa fa-comments"></i>
            <i class="fa fa-thumbs-up"></i>
            <i class="fa fa-thumbs-down"></i>
          </div>
        </div>
      </article>
    </div>
  {% endfor %}
  {% else %}
    <p> This post has no comments yet</p>
  {%endif%}
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete this pitch?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('pitches.delete_pitch', pitch_id=pitch.id) }}" method="POST">
            <input type="submit" class="btn btn-danger" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
   
{% endblock content %}

app/templates/profile.html
{% extends 'layout.html' %}

{% import 'macros.html' as macro%}

{% block content %}
  <div class="container content">
    <div class="row">
      <div class="col-md-3 user-media">
        <h2 class="article-title text-center mb-4" style="font-weight: bold; font-size: 40px;"> <u>User profile</u></h2>
        <div class="media">
          <img src="{{ image_file }}" alt="" class="rounded-circle account-img" width=150, height=150>
          <div class="media-body">
            <h2 class="account-heading"> {{ user.username }}</h2>
            {% if current_user.is_authenticated %}
            <p class="text-secondary">  {{ user.email }}</p>
            {% endif %}
          </div>
        </div>   
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-8">
        <h2 class="article-title text-center mt-4" style="font-weight: bold; font-size: 40px;"> <u>Pitches by {{ user.username }} ({{ pitches.count() }}) </u> </h2>
        {{ macro.displayPitchList(pitches) }}
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/user_pitches.html
{% import 'macros.html' as macro%}

{% extends "layout.html" %}

{% block content %}

  {{ macro.displayPitchList(pitches) }}

{% endblock content %}